//! Record what a program writes to a terminal, byte for byte and with the
//! timing intact.
//!
//! A0 of docs/roadmap/agentic.md. Every sprint on that roadmap claims agents
//! need something; this is where the claim gets a source. The existing bench
//! corpora were generated by a Python script from a description of what
//! output looks like. These are recordings of what it actually is.
//!
//!   zig build record -- bench/corpus/agent-claude.bin -- claude -p "..."
//!
//! Two files come out. The `.bin` is the raw byte stream, the same shape as
//! the other corpora, so `zig build bench` can feed it through the parser.
//! The `.timing` beside it is one line per read -- nanoseconds since the
//! first byte, and how many bytes arrived -- which is what makes questions
//! like "writes per second" and "longest burst" answerable. `script(1)` on
//! macOS can record timing too, in a format nobody wants to parse; we own a
//! pty already, so this is a hundred lines instead.
//!
//! The terminal is not involved: this records the child's output before
//! anything interprets it.

const std = @import("std");
const Pty = @import("pty.zig").Pty;

/// Wide enough that an agent redrawing a full screen is not reshaped by the
/// recording, and a common size for a real window.
const default_cols = 120;
const default_rows = 40;

/// Give up if the child produces nothing for this long. Agents think for a
/// while, so this is generous; it exists so a recording cannot hang a build.
const idle_timeout_ms = 120_000;

/// A scripted keystroke: send these bytes this long after the recording
/// started. Interactive TUIs are the whole point of recording an agent --
/// `claude -p` emits one escape byte in a kilobyte, because it is not
/// drawing anything. Driving the real interface is what produces the
/// spinners, the cursor-up-and-redraw cycles and the mode changes that the
/// protocol audit is about.
const Key = struct { at_ms: u64, bytes: []const u8 };

/// Parse `--send 1500:hello\r` into a keystroke. Escapes: \r \n \t \e
/// \\ and \xNN.
fn parseKey(gpa: std.mem.Allocator, spec: []const u8) !Key {
    const colon = std.mem.indexOfScalar(u8, spec, ':') orelse return error.BadSendSpec;
    const at_ms = try std.fmt.parseInt(u64, spec[0..colon], 10);
    const raw = spec[colon + 1 ..];

    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(gpa);
    var i: usize = 0;
    while (i < raw.len) : (i += 1) {
        if (raw[i] != '\\' or i + 1 >= raw.len) {
            try out.append(gpa, raw[i]);
            continue;
        }
        i += 1;
        switch (raw[i]) {
            'r' => try out.append(gpa, '\r'),
            'n' => try out.append(gpa, '\n'),
            't' => try out.append(gpa, '\t'),
            'e' => try out.append(gpa, 0x1b),
            '\\' => try out.append(gpa, '\\'),
            'x' => {
                if (i + 2 >= raw.len) return error.BadSendSpec;
                try out.append(gpa, try std.fmt.parseInt(u8, raw[i + 1 .. i + 3], 16));
                i += 2;
            },
            else => try out.append(gpa, raw[i]),
        }
    }
    return .{ .at_ms = at_ms, .bytes = try out.toOwnedSlice(gpa) };
}

fn nowNs() u64 {
    var ts: std.c.timespec = undefined;
    _ = std.c.clock_gettime(.MONOTONIC, &ts);
    return @as(u64, @intCast(ts.sec)) * 1_000_000_000 + @as(u64, @intCast(ts.nsec));
}

pub fn main(init: std.process.Init.Minimal) !void {
    var threaded: std.Io.Threaded = .init(std.heap.page_allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();

    var gpa_state: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa_state.deinit();
    const gpa = gpa_state.allocator();

    // record <out.bin> -- <command> [args...]
    const argv = init.args.vector;
    var sep: ?usize = null;
    for (argv, 0..) |a, i| {
        if (std.mem.eql(u8, std.mem.span(a), "--")) {
            sep = i;
            break;
        }
    }
    if (argv.len < 4 or sep == null or sep.? + 1 >= argv.len) {
        std.debug.print(
            \\usage: record <out.bin> -- <command> [args...]
            \\
            \\Records the command's terminal output to <out.bin> and its
            \\timing to <out.bin>.timing.
            \\
        , .{});
        std.process.exit(2);
    }
    const out_path = std.mem.span(argv[1]);
    const command = argv[sep.? + 1 ..];

    // --send MS:BYTES, in order. Everything between the output path and the
    // `--` is an option for the recorder itself.
    var keys: std.ArrayList(Key) = .empty;
    defer {
        for (keys.items) |k| gpa.free(k.bytes);
        keys.deinit(gpa);
    }
    var stop_after_ms: u64 = 0;
    {
        var i: usize = 2;
        while (i < sep.?) : (i += 1) {
            const a = std.mem.span(argv[i]);
            if (std.mem.eql(u8, a, "--send") and i + 1 < sep.?) {
                i += 1;
                try keys.append(gpa, try parseKey(gpa, std.mem.span(argv[i])));
            } else if (std.mem.eql(u8, a, "--stop-after") and i + 1 < sep.?) {
                i += 1;
                stop_after_ms = try std.fmt.parseInt(u64, std.mem.span(argv[i]), 10);
            }
        }
    }

    var pty = try Pty.openCommand(default_cols, default_rows, command);
    defer pty.deinit();
    pty.setNonBlocking();

    var raw: std.ArrayList(u8) = .empty;
    defer raw.deinit(gpa);
    var timing: std.ArrayList(u8) = .empty;
    defer timing.deinit(gpa);

    var buf: [65536]u8 = undefined;
    var started: ?u64 = null;
    var reads: u64 = 0;
    var next_key: usize = 0;
    const begin = nowNs();

    while (true) {
        // Keystrokes are scheduled from the moment the child started, not
        // from its first byte: a TUI that draws nothing until it is typed
        // at would otherwise never be typed at.
        const elapsed_ms = (nowNs() - begin) / std.time.ns_per_ms;
        while (next_key < keys.items.len and keys.items[next_key].at_ms <= elapsed_ms) {
            pty.writeAll(keys.items[next_key].bytes) catch {};
            next_key += 1;
        }
        if (stop_after_ms > 0 and elapsed_ms >= stop_after_ms) break;

        // Short waits while there are keystrokes left to send or a deadline
        // to honour, so neither is missed by sitting in poll.
        const pending = next_key < keys.items.len or stop_after_ms > 0;
        if (!pty.waitReadable(if (pending) 20 else idle_timeout_ms)) {
            if (pending) continue;
            break;
        }
        const n = pty.read(&buf) catch |err| switch (err) {
            error.WouldBlock => continue,
            else => break,
        };
        if (n == 0) break; // the child closed the terminal

        const now = nowNs();
        if (started == null) started = now;
        try raw.appendSlice(gpa, buf[0..n]);
        // One line per read, because a read boundary is a write boundary:
        // it is what the terminal is actually handed at once.
        var line: [64]u8 = undefined;
        const text = try std.fmt.bufPrint(&line, "{d} {d}\n", .{ now - started.?, n });
        try timing.appendSlice(gpa, text);
        reads += 1;
    }

    const elapsed = if (started) |s| nowNs() - s else 0;

    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = raw.items });
    const timing_path = try std.fmt.allocPrint(gpa, "{s}.timing", .{out_path});
    defer gpa.free(timing_path);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = timing_path, .data = timing.items });

    const secs = @as(f64, @floatFromInt(elapsed)) / 1e9;
    std.debug.print(
        "recorded {d} bytes in {d} writes over {d:.1}s ({d:.0} bytes/write, {d:.1} writes/s) -> {s}\n",
        .{
            raw.items.len,
            reads,
            secs,
            if (reads > 0) @as(f64, @floatFromInt(raw.items.len)) / @as(f64, @floatFromInt(reads)) else 0,
            if (secs > 0) @as(f64, @floatFromInt(reads)) / secs else 0,
            out_path,
        },
    );
}
